### ISSUE TITLE
Runtime Error 206

### ISSUE THREAD

**Issue by adem0x** [DGH2112/SynEdit-2-1-0-with-Theming#1]
I kept getting 'Runtime Error 206' when running any of the demos.

After chasing around a little, I found that the initialization code in SynEdit.pas needs to cater for the case when TStyleManager.Engine is nil.

So, after altering the relevant part (see below) the error vanished and it runs OK.

[I am not sure if theming will work after this, but it sure does without themes.]

```
var
  StyleEngine1: TCustomStyleEngine;

initialization

[....]

StyleEngine1 := TStyleManager.Engine;
if Assigned(StyleEngine1) then
  StyleEngine1.RegisterStyleHook(TSynEdit, TMemoStyleHook);

finalization

[....]

end.
```

**Comment by DGH2112** [comment]
Which version of RAD Studio were you using as this code has only been tested in some of the 10.x versions? Also are you using this in conjunction with my apps or in an app of your own.
Note: this was set-up as a subproject for 2 apps of my own, one is not complete (GitEditor) and the other is private. It was set-up before GitHub allows private repositories.

**Comment by DGH2112** [comment]
Sorry pressed the wrong button... Still open.

**Comment by adem0x** [comment]
I am using it in my own app with Delphi 10.3 Rio.

I needed SynEdit because it  highlighters. Theming wasn't what I was after. I opted for this fork seemed a more recent one <g>

**Comment by DGH2112** [comment]
This isn't a more recent fork as its version 2.1.0 which was October 2017. The live version on GitHub (https://github.com/SynEdit/SynEdit) will have updates that this will not.
I will address this issue as there are a couple of other things I've seen that require correcting.

**Comment by adem0x** [comment]
It appears my decision wasn't exactly what I intended.
I'll switch to live version, then.
Thank you.

**Comment by DGH2112** [comment]
I've placed guards around he Style Hooks and this therefore should be fixed.
